In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

import sys
import os

# Add the library path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.insert(0, project_root)

from ex_fuzzy_reg.rules_reg_utils import generate_triangular_partitions
from ex_fuzzy_reg.evolutionary_fit_reg import BaseFuzzyRulesRegressor

np.set_printoptions(suppress=True)

In [2]:
# TV,Radio,Newspaper,Sales
advertising_data = np.loadtxt('datasets/advertising.csv', delimiter=',', skiprows=1)
label_names = ["TV", "Radio", "Newspaper", "Sales"]

X = advertising_data[:, :-1]
y = advertising_data[:, -1].reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=12)

print("First 10 samples:")
print(np.hstack((X_test[:10], y_test[:10])))

First 10 samples:
[[228.3  16.9  26.2  20.5]
 [ 56.2   5.7  29.7   8.7]
 [ 19.6  20.1  17.    7.6]
 [237.4   5.1  23.5  17.5]
 [102.7  29.6   8.4  14. ]
 [214.7  24.    4.   17.4]
 [261.3  42.7  54.7  24.2]
 [ 97.2   1.5  30.   13.2]
 [117.2  14.7   5.4  11.9]
 [120.2  19.6  11.6  13.2]]


In [ ]:
fuzzy_variables = generate_triangular_partitions(advertising_data, n_labels=3, fv_label_names=label_names)

antecedents = fuzzy_variables[:-1]
consequent = fuzzy_variables[-1]

bfrr = BaseFuzzyRulesRegressor(fuzzy_set_type='triangular', antecedents=antecedents, consequent=consequent, n_ants=3, verbose=True)
bfrr.fit(X_train, y_train)

y_pred = bfrr.predict(X_test)
print(f"First 10 predicted sales:\n{y_pred[:10]}")

Using evolutionary backend: pymoo
4 3


IndexError: list index out of range

In [ ]:
MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")