In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

import sys
import os

# Add the library path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.insert(0, project_root)

from ex_fuzzy_reg.rules_reg_utils import generate_triangular_partitions, generate_trapezoidal_partitions
from ex_fuzzy_reg.evolutionary_fit_reg import BaseFuzzyRulesRegressor

np.set_printoptions(suppress=True)

In [2]:
# TV,Radio,Newspaper,Sales
advertising_data = np.loadtxt('datasets/advertising.csv', delimiter=',', skiprows=1)
label_names = ["TV", "Radio", "Newspaper", "Sales"]

X = advertising_data[:, :-1]
y = advertising_data[:, -1].reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=12)

print("First 10 samples:")
print(np.hstack((X_test[:10], y_test[:10])))

First 10 samples:
[[228.3  16.9  26.2  20.5]
 [ 56.2   5.7  29.7   8.7]
 [ 19.6  20.1  17.    7.6]
 [237.4   5.1  23.5  17.5]
 [102.7  29.6   8.4  14. ]
 [214.7  24.    4.   17.4]
 [261.3  42.7  54.7  24.2]
 [ 97.2   1.5  30.   13.2]
 [117.2  14.7   5.4  11.9]
 [120.2  19.6  11.6  13.2]]


In [ ]:
fuzzy_variables = generate_triangular_partitions(advertising_data, n_labels=3, fv_label_names=label_names)
#fuzzy_variables = generate_trapezoidal_partitions(advertising_data, n_labels=3, fv_label_names=label_names)

antecedents = fuzzy_variables[:-1]
consequent = fuzzy_variables[-1]

bfrr = BaseFuzzyRulesRegressor(n_rules=20, fuzzy_set_type='triangular', antecedents=antecedents, consequent=consequent, n_ants=3, verbose=True)
#bfrr = BaseFuzzyRulesRegressor(n_rules=15, fuzzy_set_type='trapezoidal', antecedents=antecedents, consequent=consequent, n_ants=3, verbose=True)
bfrr.fit(X_train, y_train)

Using evolutionary backend: pymoo
     1 |       30 |  0.2099116623 |  0.1509547283
     2 |       60 |  0.1915550633 |  0.1509547283
     3 |       90 |  0.1825173066 |  0.1509547283
     4 |      120 |  0.1735863655 |  0.1509547283
     5 |      150 |  0.1564822945 |  0.1509547283
     6 |      180 |  0.1509547283 |  0.1509547283
     7 |      210 |  0.1509547283 |  0.1509547283
     8 |      240 |  0.1509547283 |  0.1509547283
     9 |      270 |  0.1509547283 |  0.1509547283
    10 |      300 |  0.1508160704 |  0.1467949918
    11 |      330 |  0.1503276498 |  0.1450039553
    12 |      360 |  0.1489224413 |  0.1450039553
    13 |      390 |  0.1460363124 |  0.1450039553
    14 |      420 |  0.1449781481 |  0.1446168474
    15 |      450 |  0.1448030465 |  0.1409122316
    16 |      480 |  0.1443037759 |  0.1409122316
    17 |      510 |  0.1434219915 |  0.1409122316
    18 |      540 |  0.1415262287 |  0.1409122316
    19 |      570 |  0.1409122316 |  0.1409122316
    20 |      60

In [9]:
y_pred = bfrr.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 12.072587702888983
Mean Absolute Error: 2.895069201158622
R² Score: 0.6032443176885205
Root Mean Squared Error: 3.4745629513492746


In [7]:
y_pred = bfrr.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 9.54872215198325
Mean Absolute Error: 2.5130805676752126
R² Score: 0.6861890867269277
Root Mean Squared Error: 3.090100670202065


### Different models to compare the results:

In [15]:
# TODO: add brief explanation for the models used
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

- #### Linear Regression:

In [16]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred = lin_reg.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 1.9474231382316725
Mean Absolute Error: 1.0410039192230955
R² Score: 0.93599953754957
Root Mean Squared Error: 1.3955010348371915


- #### K-Nearest-Neighbors:

In [17]:
knn = KNeighborsRegressor()
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 1.5120266666666669
Mean Absolute Error: 0.9546666666666666
R² Score: 0.9503084850928084
Root Mean Squared Error: 1.229644935201486


### Comparing BaseFuzzyRulesRegressor in different datasets:

- #### Diabetes dataset:

In [ ]:
# TODO: add brief explanation for the datasets used
from sklearn.datasets import load_diabetes

diabetes = load_diabetes(scaled=False)

X, y = diabetes.data, diabetes.target
print(X.shape, y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=12)

(442, 10) (442,)


In [ ]:
fuzzy_variables = generate_triangular_partitions(diabetes, n_labels=3, fv_label_names=label_names)

antecedents = fuzzy_variables[:-1]
consequent = fuzzy_variables[-1]

bfrr = BaseFuzzyRulesRegressor(fuzzy_set_type='triangular', antecedents=antecedents, consequent=consequent, n_ants=3, verbose=True)
bfrr.fit(X_train, y_train)

y_pred = bfrr.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred = lin_reg.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

In [ ]:
knn = KNeighborsRegressor()
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

- #### California housing dataset:

In [ ]:
from sklearn.datasets import fetch_california_housing
X, y = fetch_california_housing(download_if_missing='.', return_X_y=True)