In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error

import sys
import os

# Add the library path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.insert(0, project_root)

from ex_fuzzy_reg.fuzzy_sets import FUZZY_SETS
from ex_fuzzy_reg.rules_reg_utils import generate_partitions
from ex_fuzzy_reg.regressors import MamdamiFIS

np.set_printoptions(suppress=True)

#### Advertising Dataset:

In [2]:
# TV,Radio,Newspaper,Sales
advertising_data = np.loadtxt('datasets/advertising.csv', delimiter=',', skiprows=1)
label_names = ["TV", "Radio", "Newspaper", "Sales"]

X = advertising_data[:, :-1]
y = advertising_data[:, -1].reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=12)

print("First 10 samples:")
print(np.hstack((X_test[:10], y_test[:10])))

First 10 samples:
[[228.3  16.9  26.2  20.5]
 [ 56.2   5.7  29.7   8.7]
 [ 19.6  20.1  17.    7.6]
 [237.4   5.1  23.5  17.5]
 [102.7  29.6   8.4  14. ]
 [214.7  24.    4.   17.4]
 [261.3  42.7  54.7  24.2]
 [ 97.2   1.5  30.   13.2]
 [117.2  14.7   5.4  11.9]
 [120.2  19.6  11.6  13.2]]


In [3]:
fuzzy_variables = generate_partitions(advertising_data, n_labels=3, fv_label_names=label_names)

print("Variables generated:")
for i in range(len(fuzzy_variables)):
    print(fuzzy_variables[i].name)
    for j in range(len(fuzzy_variables[i].linguistic_variables)):
        print(fuzzy_variables[i].linguistic_variables[j])
    print()

Variables generated:
TV
low TV (t1) - [0.7, 0.7, 148.54999999999998] - 1.0
medium TV (t1) - [0.7, 148.54999999999998, 296.4] - 1.0
high TV (t1) - [148.54999999999998, 296.4, 296.4] - 1.0

Radio
low Radio (t1) - [0.0, 0.0, 24.8] - 1.0
medium Radio (t1) - [0.0, 24.8, 49.6] - 1.0
high Radio (t1) - [24.8, 49.6, 49.6] - 1.0

Newspaper
low Newspaper (t1) - [0.3, 0.3, 57.15] - 1.0
medium Newspaper (t1) - [0.3, 57.15, 114.0] - 1.0
high Newspaper (t1) - [57.15, 114.0, 114.0] - 1.0

Sales
low Sales (t1) - [1.6, 1.6, 14.3] - 1.0
medium Sales (t1) - [1.6, 14.3, 27.0] - 1.0
high Sales (t1) - [14.3, 27.0, 27.0] - 1.0



In [4]:
mamdaniFIS = MamdamiFIS(FUZZY_SETS.t1, linguistic_variables=fuzzy_variables)
mamdaniFIS.fit(X_train, y_train)
y_pred = mamdaniFIS.predict(X_test)

print(f"First 10 predicted sales:\n{y_pred[:10]}")

First 10 predicted sales:
[[15.59154172]
 [11.73083321]
 [15.02601278]
 [15.00585704]
 [15.27149411]
 [14.62197158]
 [18.07523443]
 [13.76320901]
 [14.56652406]
 [15.7673468 ]]


In [5]:
MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 17.344043903468336
Mean Absolute Error: 3.530451629157713
R² Score: 0.4518317350357668
Root Mean Squared Error: 4.164618098153579


#### Salary Data Dataset:

In [6]:
# Age,Gender,Education Level,Job Title,Years of Experience,Salary
# relevant for the demo: Age,Years of Experience,Salary
salary_data = np.loadtxt('datasets/salary_data.csv', delimiter=',', skiprows=1, usecols=(0, 4, 5))
label_names = ["Age", "Years of Experience", "Salary"]

X = salary_data[:, :-1]
y = salary_data[:, -1].reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=25)

print("First 10 samples:")
print(np.hstack((X_test[:10], y_test[:10])))

First 10 samples:
[[    29.      6. 150000.]
 [    35.      8. 145000.]
 [    30.      4.  58000.]
 [    31.      4.  65000.]
 [    27.      3.  80000.]
 [    29.      6. 180000.]
 [    26.      5.  85000.]
 [    39.     15. 200000.]
 [    31.      6.  85000.]
 [    36.      9. 150000.]]


In [7]:
fuzzy_variables = generate_partitions(salary_data, n_labels=3, fv_label_names=label_names)

print("Variables generated:")
for i in range(len(fuzzy_variables)):
    print(fuzzy_variables[i].name)
    for j in range(len(fuzzy_variables[i].linguistic_variables)):
        print(fuzzy_variables[i].linguistic_variables[j])
    print()

Variables generated:
Age
low Age (t1) - [21.0, 21.0, 41.5] - 1.0
medium Age (t1) - [21.0, 41.5, 62.0] - 1.0
high Age (t1) - [41.5, 62.0, 62.0] - 1.0

Years of Experience
low Years of Experience (t1) - [0.0, 0.0, 17.0] - 1.0
medium Years of Experience (t1) - [0.0, 17.0, 34.0] - 1.0
high Years of Experience (t1) - [17.0, 34.0, 34.0] - 1.0

Salary
low Salary (t1) - [25000.0, 25000.0, 137500.0] - 1.0
medium Salary (t1) - [25000.0, 137500.0, 250000.0] - 1.0
high Salary (t1) - [137500.0, 250000.0, 250000.0] - 1.0



In [8]:
mamdaniFIS = MamdamiFIS(FUZZY_SETS.t1, linguistic_variables=fuzzy_variables)
mamdaniFIS.fit(X_train, y_train)
y_pred = mamdaniFIS.predict(X_test)

print(f"First 10 predicted salaries:\n{y_pred[:10]}")

First 10 predicted salaries:
[[118707.9763715 ]
 [129985.87311328]
 [105688.99483004]
 [107811.30797466]
 [ 94433.3603579 ]
 [118707.9763715 ]
 [106943.27472568]
 [156402.43902439]
 [123173.60918214]
 [134092.45314287]]


In [9]:
MSE = mean_squared_error(y_test, y_pred)
MAE = mean_absolute_error(y_test, y_pred)
R2 = r2_score(y_test, y_pred)
RMSE = root_mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {MSE}")
print(f"Mean Absolute Error: {MAE}")
print(f"R² Score: {R2}")
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 1152853511.48526
Mean Absolute Error: 29803.406760901245
R² Score: 0.5834056973632173
Root Mean Squared Error: 33953.696580567776
